---
abstract: 'A comprehensive, DWIM-featured client to the MetaCPAN API'
author:
  - 'Sawyer X <xsawyerx@cpan.org>'
  - 'Mickey Nasriachi <mickey@cpan.org>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.28
  Test::Fatal: 0
  Test::More: 0
  Test::Requires: 0
  base: 0
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 0
  Module::Build: 0.28
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MetaCPAN-Client
no_index:
  file:
    - README.pod
requires:
  Carp: 0
  HTTP::Tiny: 0
  JSON::MaybeXS: 0
  Moo: 0
  Moo::Role: 0
  Safe::Isa: 0
  Search::Elasticsearch: 1.10
  Search::Elasticsearch::Scroll: 0
  Try::Tiny: 0
  strict: 0
  warnings: 0
resources:
  repository: https://github.com/CPAN-API/metacpan-client.git
version: 1.008000
